version: '2'
services:
  app:
    container_name: checkout_system
    image: checkout_system_image
    build: .
    networks:
      - main_network
    volumes:
      - ./src:/app/src
    ports:
      - 5000:5000
networks:
  main_network:
    driver: bridge
